services:
  turbacz:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_started
      mosquitto:
        condition: service_started
      victoriametrics:
        condition: service_started
    environment:
      - TURBACZ_CONFIG_PATH=/app/turbacz.toml
    volumes:
      - ./turbacz.toml:/app/turbacz.toml
    restart: unless-stopped

  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: turbacz
      POSTGRES_USER: turbacz
      POSTGRES_PASSWORD: turbacz
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  mosquitto:
    image: eclipse-mosquitto:2.0
    ports:
      - "1883:1883"
      - "9883:9883"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
      - mosquitto_data:/mosquitto/data
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    depends_on:
      victoriametrics:
        condition: service_started
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SECURITY_ADMIN_USER=admin
    volumes:
      - grafana_data:/var/lib/grafana
    restart: unless-stopped

  victoriametrics:
    image: victoriametrics/victoria-metrics:latest
    ports:
      - "8428:8428"
    volumes:
      - victoriametrics_data:/victoriametrics_data
    restart: unless-stopped

volumes:
  postgres_data:
  mosquitto_data:
  grafana_data:
  victoriametrics_data: