global:
  scrape_interval: 15s
  scrape_timeout: 5s

scrape_configs:
  - job_name: turbacz
    metrics_path: /metrics
    authorization:
      type: Bearer
      credentials_file: /etc/turbacz_scrape_token
    static_configs:
      - targets:
          - turbacz:8000
